import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Grid from '@mui/material/Grid';
import Card from '@mui/material/Card';
import CardActions from '@mui/material/CardActions';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import Typography from '@mui/material/Typography';
const Home: NextPage = () => {
  return (
    <div  >
      <Head>
        <title>Haaken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Grid container spacing={0}>
          <Grid item xs>
            <img style={{ width: '100%' }} src="https://haaken.qodeinteractive.com/wp-content/uploads/2021/01/h1-slider-images-1.jpg" alt="" />
          </Grid>
          <Grid item xs>
            <img style={{ width: '100%' }} src="https://haaken.qodeinteractive.com/wp-content/uploads/2021/01/h1-slider-images-6.jpg" alt="" />
          </Grid>
        </Grid>
        <div className={styles.sevenpic}>
          <Grid container spacing={2} >
            <Grid item xs={8}>
              <img width='1225' height='650' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/12/h1-masonty-img-1-2-1260x650.jpg" alt="" />
            </Grid>
            <Grid item xs={4}>
              <img width='602' height='650' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/h1-masonty-img-2.jpg" alt="" />
            </Grid>
          </Grid>
          <Grid style={{ marginTop: '1%' }} container spacing={2} >
            <Grid item xs={8}>
              <Grid container spacing={2} >
                <Grid item xs={6}>
                  <img width='600' height='612' src="https://haaken.qodeinteractive.com/wp-content/uploads/2021/01/h1-masonty-img-3.jpg" alt="" />
                </Grid>
                <Grid item xs={6}>
                  <img width='600' height='612' src="https://haaken.qodeinteractive.com/wp-content/uploads/2021/01/h1-masonty-img-4.jpg" alt="" />
                </Grid>
              </Grid>
            </Grid>
            <Grid item xs={4}>
              <img width='600' height='612' src="https://haaken.qodeinteractive.com/wp-content/uploads/2021/01/h1-masonty-img-5.jpg" alt="" />
            </Grid>
          </Grid>
          <Grid style={{ marginTop: '1%' }} container spacing={1} >
            <Grid item xs={4}>
              <img width='602' height='650' src="https://haaken.qodeinteractive.com/wp-content/uploads/2021/01/h1-masonty-img-6.jpg" alt="" />
            </Grid>
            <Grid item xs={8}>
              <img width='1225' height='650' src="https://haaken.qodeinteractive.com/wp-content/uploads/2021/01/h1-masonty-img-7.jpg" alt="" />
            </Grid>
          </Grid>
          <div style={{ width: '100%'}}>

            <iframe src="https://player.vimeo.com/video/509220650?h=7a77033af3&amp;muted=1&amp;autoplay=1&amp;loop=1&amp;transparent=0&amp;background=1&amp;app_id=122963" allow="autoplay; fullscreen; picture-in-picture" title="DIOR SS21" data-ready="true" width='1850px' height='1052px'></iframe>
          </div>
        </div>
        {/* <div id="new-colection" style={{ padding: '134px 0 47px' }}>
          <div style={{ marginLeft: '10%' }}>
            <span style={{ fontSize: '15px' }}> FRESH AND BOLD</span>
            <h2 style={{ fontSize: '40px', letterSpacing: '6px' }}>NEW COLLECTION</h2>
          </div>
        </div> */}
        {/* <div id='translist'>
          <Grid container spacing={3}>
            <Grid item xs>
              <div id="item-vid">
                <img height='450px' width='300px' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/h1-port-img-1.jpg" alt="" />
                <h3 style={{ marginTop: '5%' }}>WEIGHT</h3>
                <a style={{ color: 'black', fontSize: '16px' }} href="#">VIEW MORE</a>
              </div>
            </Grid>
            <Grid item xs>
              <div id="item-vid">
                <img height='450px' width='300px' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/h1-port-img-2.jpg" alt="" />
                <h3 style={{ marginTop: '5%' }} >ART SHOW</h3>
                <a style={{ color: 'black', fontSize: '16px' }} href="#">VIEW MORE</a>
              </div>
            </Grid>
            <Grid item xs>
              <div id="item-vid">
                <img height='450px' width='300px' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/h1-port-img-3.jpg" alt="" />
                <h3 style={{ marginTop: '5%' }}>NEO DEMONS</h3>
                <a style={{ color: 'black', fontSize: '16px' }} href="#">VIEW MORE</a>
              </div>
            </Grid>
            <Grid item xs>
              <div id="item-vid">
                <img height='450px' width='300px' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/h1-port-img-4.jpg" alt="" />
                <h3 style={{ marginTop: '5%' }}>APE ATTACK</h3>
                <a style={{ color: 'black', fontSize: '16px' }} href="#">VIEW MORE</a>
              </div>
            </Grid>
            <Grid item xs>
              <div id="item-vid">
                <img height='450px' width='300px' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/h1-port-img-5.jpg" alt="" />
                <div  >
                  <h3 style={{ marginTop: '5%' }}>TREND</h3>
                  <a style={{ color: 'black', fontSize: '16px' }} href="#">VIEW MORE</a>
                </div>
              </div>
            </Grid>
          </Grid>
        </div> */}
        {/* <div style={{ marginTop: '5%' }}>
          <div className={styles.signup} >
            <div id="tittle-signup">
              <h4 style={{ textAlign: 'center' }} >SIGN UP FOR OUR NEWSLETTER</h4>
            </div>
            <div style={{ paddingLeft: '540px', paddingRight: '540px' }}>
              <div className={styles.inputemail}>
                <input style={{ border: 0 }} type="email" className={styles.inputtext} name="your-email" value="" placeholder="E-mail address" />
              </div>
              <button type="submit" className={styles.buttonsignup} ><span >Sign Up</span></button>
            </div>
          </div>
        </div> */}
        {/* <div id="background-video" style={{width:'100%',paddingLeft:'1%'}}>
          
              <iframe  src="https://player.vimeo.com/video/509220650?h=7a77033af3&amp;muted=1&amp;autoplay=1&amp;loop=1&amp;transparent=0&amp;background=1&amp;app_id=122963" allow="autoplay; fullscreen; picture-in-picture" title="DIOR SS21" data-ready="true" width='1888px' height='1062px'></iframe>
        </div> */}
        {/* <div style={{ padding: '134px 0 47px', marginLeft: '100px', marginRight: '240px' }}>
          <span className={styles.tittleblog}>Pretty Important</span>
          <h2 className={styles.blogpost} >Blog Posts </h2>
        </div> */}
        {/* <div id='listpost'>
          <Grid sx={{ paddingLeft: '5%' }} container spacing={1}>
            <Grid item xs={4}>
              <img height='240px' width='440px' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/h1-post-1-img.jpg" alt="" />
              <p style={{ fontSize: '14px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '.06em' }}>06/11/2020/ALBUM</p>
              <h3>LIBERATED MARKET</h3>
              <p>Lorem ipsum dolor sit amet, con sectetur adi piscing elit, sed do ei usmod tempo</p>

            </Grid>
            <Grid item xs={4}>
              <img height='240px' width='440px' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/h1-post-1-img.jpg" alt="" />
              <p style={{ fontSize: '14px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '.06em' }}>06/11/2020/ALBUM</p>
              <h3>LIBERATED MARKET</h3>
              <p>Lorem ipsum dolor sit amet, con sectetur adi piscing elit, sed do ei usmod tempo</p>

            </Grid>
            <Grid item xs={4}>
              <img height='240px' width='440px' src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/h1-post-1-img.jpg" alt="" />
              <p style={{ fontSize: '14px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '.06em' }}>06/11/2020/ALBUM</p>
              <h3>LIBERATED MARKET</h3>
              <p>Lorem ipsum dolor sit amet, con sectetur adi piscing elit, sed do ei usmod tempo</p>

            </Grid>
          </Grid>

        </div> */}

        <div id="container-pretty"  >
          <div id="content-pretty" style={{ padding: '134px 0 47px', marginLeft: '100px', marginRight: '240px' }}>
            <div id="tittle-pretty" >
              <span style={{ fontSize: '14px', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '.06em', display: 'block', marginBottom: '5px', textAlign: 'right', marginRight: '10px' }} >PRETTY IMPORTANT</span>
              <h2 style={{ textTransform: 'uppercase', fontSize: '40px', lineHeight: '1.2em', letterSpacing: '.26em', fontWeight: 700, textAlign: 'right' }} >TESTIMONIALS</h2>
            </div>
            <div style={{ marginTop: '5%' }}>
              <Grid container spacing={1}>
                <Grid item xs={4} >
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 190 193" width="190" height="193"><path d="M64.8 189c-20 0-35.4-5.3-46-16s-16-26-16-46V3h77.5v124H33.8c0 11 2.4 18.9 7.3 23.7s12.8 7.3 23.7 7.3v31zm108.5 0c-20 0-35.4-5.3-46-16s-16-26-16-46V3h77.5v124h-46.5c0 11 2.4 18.9 7.3 23.7s12.8 7.3 23.7 7.3v31z" fill="none" stroke="#000"></path></svg>
                </Grid>
                <Grid item xs={8} >
                  <div style={{ display: 'flex', flexWrap: 'wrap' }}>
                    <div style={{ textAlign: 'right', flex: '85%' }}>
                      <span style={{ fontSize: '16px' }}>“Diam vulputate ut pharetra sit amet aliquam. Neque ornare aenean euismod elementum nisi quis eleifend. Tortor dignissim convallis aenean et tortor at risus. In iaculis nunc.” </span>
                      <h4 style={{ textAlign: 'right', marginTop: '2%' }}>
                        <span style={{ fontWeight: 700 }} >
                          Louise Johnson	</span>
                      </h4>
                      <p style={{ fontSize: '16px' }} >Writer</p>
                    </div>
                    <div style={{ textAlign: 'right', flex: '15%' }}>
                      <img width="110" height="111" src="https://haaken.qodeinteractive.com/wp-content/uploads/2021/04/h1-testimonial-2.jpg" />
                    </div>
                  </div>
                </Grid>
              </Grid>
            </div>

          </div>
        </div>
        <Grid style={{ borderWidth: '0 20px 20px', borderStyle: 'solid', borderColor: '#ffffff', backgroundColor: '#e8e8f9', marginTop: '5%' }} container>
          <Grid container spacing={1} style={{ padding: '82px 0px 52px 0px', textAlign: 'center' }}>
            <Grid item xs={2}  >
              <img width="160" height="160" src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/client-1.png" />
            </Grid>
            <Grid item xs={2}  >
              <img width="160" height="160" src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/client-2.png" />
            </Grid>
            <Grid item xs={2}  >
              <img width="160" height="160" src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/client-3.png" />
            </Grid>
            <Grid item xs={2}  >
              <img width="160" height="160" src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/client-4.png" />
            </Grid>
            <Grid item xs={2}  >
              <img width="160" height="160" src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/client-5.png" />
            </Grid>
            <Grid item xs={2} >
              <img width="160" height="160" src="https://haaken.qodeinteractive.com/wp-content/uploads/2020/11/client-6.png" />
            </Grid>
          </Grid>
        </Grid>
      </main >



    </div >
  )
}

export default Home
