import { Timestamp } from 'firebase/firestore';
export interface Product {
      //Auto Generated By Cloud Function
  id?: string;
  createdAt?: Timestamp;
  createdDate?: string;
  createdBy?: string;

  Brand?: string;
  Name?: string;
  imgURL?:string;
  Price?:string;
}